// react18/ssg/src/client/components/Header.jsx
import React from "react";

const Header = ({ name, renderType, numberOfElements }) => {
  return (
    <header>
      <h1 className="header-name">
        <span>{name}</span> {renderType}
      </h1>
      <p>
        <strong>{Intl.NumberFormat("pl-PL").format(numberOfElements)}</strong>{" "}
        wyrenderowanych elementów
      </p>
    </header>
  );
};

export default Header;

// vue3/ssr/src/client/components/Header.vue
<script>
export default {
  props: ["name", "renderType", "numberOfElements"],
};
</script>

<template>
  <header class="header">
    <h1 class="header-name">
      <span>{{ name }}</span> {{ renderType }}
    </h1>
    <p>
      <strong>{{ Intl.NumberFormat("pl-PL").format(numberOfElements) }}</strong
      >{{ " " }} wyrenderowanych elementów
    </p>
  </header>
</template>
