// vue3/ssr/src/client/components/Table.vue
<template>
  <table>
    <tr>
      <th>Kolumna 1</th>
      <th>Kolumna 2</th>
      <th>Kolumna 3</th>
    </tr>

    <tr v-for="row in tableRows" :key="row.id">
      <td>{{ row.name }}</td>
      <td>{{ row.name }}</td>
      <td>{{ row.name }}</td>
    </tr>
  </table>
</template>

<script>
export default {
  props: ["tableRows"],
};
</script>

// react17/ssr/src/client/components/Table.jsx
import React from "react";

const Table = ({ tableRows }) => {
  return (
    <table>
      <tr>
        <th>Kolumna 1</th>
        <th>Kolumna 2</th>
        <th>Kolumna 3</th>
      </tr>

      {tableRows.map((row) => (
        <tr key={row.id}>
          <td>{row.name}</td>
          <td>{row.name}</td>
          <td>{row.name}</td>
        </tr>
      ))}
    </table>
  );
};

export default Table;
