// preact/csr/src/components/Table.jsx
import { h } from "preact";

const Table = ({ tableRows }) => {
  return (
    <table>
      <tr>
        <th>Kolumna 1</th>
        <th>Kolumna 2</th>
        <th>Kolumna 3</th>
      </tr>

      {tableRows.map((row) => (
        <tr key={row.id}>
          <th>{row.name}</th>
          <th>{row.name}</th>
          <th>{row.name}</th>
        </tr>
      ))}
    </table>
  );
};

export default Table;

// vue2/csr/src/components/Table.vue
<script>
export default {
  props: ["tableRows"],
};
</script>

<template>
  <table>
    <tr>
      <th>Kolumna 1</th>
      <th>Kolumna 2</th>
      <th>Kolumna 3</th>
    </tr>

    <tr v-for="row in tableRows" :key="row.id">
      <td>{{ row.name }}</td>
      <td>{{ row.name }}</td>
      <td>{{ row.name }}</td>
    </tr>
  </table>
</template>
