// vue2/ssr/src/client/App.vue
<script>
import { data, ELEMENTS } from "../../../../config";
import Counter from "./components/Counter.vue";
import Footer from "./components/Footer.vue";
import Grid from "./components/Grid.vue";
import Header from "./components/Header.vue";
import List from "./components/List.vue";
import ListItem from "./components/ListItem.vue";
import Main from "./components/Main.vue";
import Table from "./components/Table.vue";
import "./index.css";

export default {
  data() {
    return {
      listItems: data.listItems,
      tableRows: data.tableRows,
      counters: data.counters,
      ELEMENTS,
    };
  },
  components: {
    Main,
    List,
    ListItem,
    Header,
    Footer,
    Table,
    Grid,
    Counter,
  },
};
</script>

<template>
  <Main>
    <Header :name="'Vue 2'" :renderType="'SSR'" :numberOfElements="ELEMENTS" />

    <Grid>
      <Counter v-for="counter in counters" :key="counter.id">
        {{ counter.name }}
      </Counter>
    </Grid>

    <Table :tableRows="tableRows" />

    <List>
      <ListItem v-for="item in listItems" :key="item.id">
        {{ item.name }}
      </ListItem>
    </List>

    <Footer name="Vue 2 SSR" />
  </Main>
</template>

// preact/ssr/src/client/App.jsx
import { data, ELEMENTS } from "../../../../config";
import Counter from "./components/Counter";
import Footer from "./components/Footer";
import Grid from "./components/Grid";
import Header from "./components/Header";
import List from "./components/List";
import ListItem from "./components/ListItem";
import Main from "./components/Main";
import Table from "./components/Table";

function App() {
  return (
    <Main>
      <Header name="Preact" renderType="SSR" numberOfElements={ELEMENTS} />

      <Grid>
        {data.counters.map((counter) => (
          <Counter key={counter.id}>{counter.name}</Counter>
        ))}
      </Grid>

      <Table tableRows={data.tableRows} />

      <List>
        {data.listItems.map((item) => (
          <ListItem key={item.id}>{item.name}</ListItem>
        ))}
      </List>

      <Footer name="Preact SSR" />
    </Main>
  );
}

export default App;
