// vue3/csr/src/components/Table.vue
<script>
export default {
  props: ["tableRows"],
};
</script>

<template>
  <table>
    <thead>
      <tr>
        <th>Kolumna 1</th>
        <th>Kolumna 2</th>
        <th>Kolumna 3</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="row in tableRows" :key="row.id">
        <td>{{ row.name }}</td>
        <td>{{ row.name }}</td>
        <td>{{ row.name }}</td>
      </tr>
    </tbody>
  </table>
</template>

// preact/ssg/src/client/components/Table.jsx
import { h } from "preact";

const Table = ({ tableRows }) => {
  return (
    <table>
      <thead>
        <tr>
          <th>Kolumna 1</th>
          <th>Kolumna 2</th>
          <th>Kolumna 3</th>
        </tr>
      </thead>
      <tbody>
        {tableRows.map((row) => (
          <tr key={row.id}>
            <th>{row.name}</th>
            <th>{row.name}</th>
            <th>{row.name}</th>
          </tr>
        ))}
      </tbody>
    </table>
  );
};

export default Table;
